/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;
import javax.swing.JOptionPane;
import services.CursoImpl;
import services.EditarService;


/**
 *
 * @author wil
 */
public class EditarCursos extends javax.swing.JFrame {
    int xMouse, yMouse;

   private EditarService<Curso> editarService;
    /**
     * Creates new form EditarCurso
     */
    public EditarCursos() {
        initComponents();
        
        editarService = new CursoImpl();
        
         for(Curso e : Loginb.Cursos){
            jComboBox1.addItem(e.codigo);
        }
         for(Profesor e : Loginb.profesores){
            jComboBox_profeNew.addItem(e.usuario);
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton_editProfe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDateChooser_fechafNew = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_idNew = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_horafNew = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_horaiNew = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_seccionNew = new javax.swing.JTextField();
        jComboBox_profeNew = new javax.swing.JComboBox<>();
        jDateChooser_fechaiNew = new com.toedter.calendar.JDateChooser();
        jTextField_nombreNew = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton_editProfe.setText("Guardar");
        jButton_editProfe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton_editProfeFocusLost(evt);
            }
        });
        jButton_editProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editProfeActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser_fechafNew.setDateFormatString("d/MM/yyyy");

        jLabel6.setText("Fecha de finalizacion");

        jLabel1.setText("Codigo");

        jLabel7.setText("Hora de Inicio:");

        jLabel_idNew.setEditable(false);
        jLabel_idNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_idNewActionPerformed(evt);
            }
        });

        jLabel8.setText("Hora de fin:");

        jLabel2.setText("Nombre");

        jLabel3.setText("Seccion");

        jLabel4.setText("Profesor");

        jTextField3_seccionNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_seccionNewActionPerformed(evt);
            }
        });

        jComboBox_profeNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_profeNewActionPerformed(evt);
            }
        });

        jDateChooser_fechaiNew.setDateFormatString("d/MM/yyyy");
        jDateChooser_fechaiNew.setMaxSelectableDate(new java.util.Date(253370790118000L));

        jTextField_nombreNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreNewActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de inicio");

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox_profeNew, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_idNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nombreNew, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3_seccionNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(50, 50, 50)
                                .addComponent(jButton_editProfe))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser_fechaiNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser_fechafNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_horaiNew, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_horafNew, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_idNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombreNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3_seccionNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_profeNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_fechaiNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_fechafNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_horaiNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_horafNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_editProfe)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedCurso = jComboBox1.getSelectedItem().toString();
        Curso cursoSeleccionado = editarService.buscarElementoId(selectedCurso);

        if (cursoSeleccionado != null) {
            jLabel_idNew.setText(cursoSeleccionado.codigo);
            jTextField_nombreNew.setText(cursoSeleccionado.nombre);
            jTextField_horaiNew.setText(cursoSeleccionado.horaIni);
            jTextField_horafNew.setText(cursoSeleccionado.horaFin);
            jTextField3_seccionNew.setText(cursoSeleccionado.seccion);
            jComboBox_profeNew.setSelectedItem(cursoSeleccionado.profesor);
            jDateChooser_fechaiNew.setDate(cursoSeleccionado.fechaIni);
            jDateChooser_fechafNew.setDate(cursoSeleccionado.fechaFin);
            
        } else {
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton_editProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editProfeActionPerformed
        String selectedCurso = jComboBox1.getSelectedItem().toString();
        Curso cursoSeleccionado = editarService.buscarElementoId(selectedCurso);//buscarElemento
    
    if (cursoSeleccionado != null) {
        // Actualizar los datos del curso seleccionado con los valores ingresados en los componentes
        cursoSeleccionado.nombre = jTextField_nombreNew.getText();
        cursoSeleccionado.horaIni = jTextField_horaiNew.getText();
        cursoSeleccionado.horaFin = jTextField_horafNew.getText();
        cursoSeleccionado.seccion = jTextField3_seccionNew.getText();
        cursoSeleccionado.profesor = jComboBox_profeNew.getSelectedItem().toString();
        cursoSeleccionado.fechaIni = jDateChooser_fechaiNew.getDate();
        cursoSeleccionado.fechaFin = jDateChooser_fechafNew.getDate();
       
        JOptionPane.showMessageDialog(this, "Curso actualizado exitosamente.");
         BinManager.guardarCursos(Loginb.Cursos);
        
        
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un curso para editarlo.");
    }
     jLabel_idNew.setText("");
        jTextField_nombreNew.setText("");
        jTextField_horaiNew.setText("");
        jTextField_horafNew.setText("");
        jTextField3_seccionNew.setText("");
        jComboBox1.setSelectedIndex(0); 
        jComboBox_profeNew.setSelectedIndex(-1);
        jDateChooser_fechaiNew.setDate(null); 
        jDateChooser_fechafNew.setDate(null); 
           
        
    }//GEN-LAST:event_jButton_editProfeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_idNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_idNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_idNewActionPerformed

    private void jTextField3_seccionNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_seccionNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_seccionNewActionPerformed

    private void jComboBox_profeNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_profeNewActionPerformed
        // TODO add yourthis.repaint(); handling code here:
    }//GEN-LAST:event_jComboBox_profeNewActionPerformed

    private void jTextField_nombreNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreNewActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jButton_editProfeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton_editProfeFocusLost
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton_editProfeFocusLost

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y- yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_editProfe;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_profeNew;
    private com.toedter.calendar.JDateChooser jDateChooser_fechafNew;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaiNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jLabel_idNew;
    private javax.swing.JTextField jTextField3_seccionNew;
    private javax.swing.JTextField jTextField_horafNew;
    private javax.swing.JTextField jTextField_horaiNew;
    private javax.swing.JTextField jTextField_nombreNew;
    // End of variables declaration//GEN-END:variables
}
