/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;

import java.io.IOException;
import java.text.ParseException;
import services.CursoImpl;
import services.EditarService;
import services.ProfesorImpl;

/**
 *
 * @author wil
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_consultarProfes = new javax.swing.JButton();
        btn_consultaAlumnos = new javax.swing.JButton();
        btn_crearEstu = new javax.swing.JButton();
        btn_crearEstudiante = new javax.swing.JButton();
        btn_crearProfesor = new javax.swing.JButton();
        btn_consultarCursos = new javax.swing.JButton();
        btn_crearCursos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_editarAlumnos = new javax.swing.JButton();
        jButton_editarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Editar Profesor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_consultarProfes.setText("Consultar Profesores");
        btn_consultarProfes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarProfesActionPerformed(evt);
            }
        });

        btn_consultaAlumnos.setText("Consultar alumnos de Cursos");
        btn_consultaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaAlumnosActionPerformed(evt);
            }
        });

        btn_crearEstu.setText("Asignar Estudiantes");
        btn_crearEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearEstuActionPerformed(evt);
            }
        });

        btn_crearEstudiante.setText("Crear estudiante");
        btn_crearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearEstudianteActionPerformed(evt);
            }
        });

        btn_crearProfesor.setText("Crear Profesor");
        btn_crearProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearProfesorActionPerformed(evt);
            }
        });

        btn_consultarCursos.setText("Consultar Cursos");
        btn_consultarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarCursosActionPerformed(evt);
            }
        });

        btn_crearCursos.setText("Crear Cursos");
        btn_crearCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearCursosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: Wilson López");

        jButton5.setText("Consultar Alumnos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Importar Cursos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("ExportarXML");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Importar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_editarAlumnos.setText("Editar Alumnos");
        btn_editarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarAlumnosActionPerformed(evt);
            }
        });

        jButton_editarCurso.setText("Editar Cursos");
        jButton_editarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_crearCursos)
                            .addGap(76, 76, 76)
                            .addComponent(btn_crearProfesor)
                            .addGap(66, 66, 66)
                            .addComponent(btn_crearEstudiante))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_consultarCursos)
                            .addGap(31, 31, 31)
                            .addComponent(jButton1)
                            .addGap(86, 86, 86)
                            .addComponent(btn_crearEstu))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_editarCurso)
                            .addGap(76, 76, 76)
                            .addComponent(btn_consultarProfes)
                            .addGap(26, 26, 26)
                            .addComponent(jButton5)
                            .addGap(1, 1, 1)
                            .addComponent(btn_editarAlumnos))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addGap(227, 227, 227)
                            .addComponent(btn_consultaAlumnos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(380, 380, 380)
                            .addComponent(jButton2)
                            .addGap(4, 4, 4)
                            .addComponent(jButton3)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_crearCursos)
                        .addComponent(btn_crearProfesor)
                        .addComponent(btn_crearEstudiante))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_crearEstu)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_consultarCursos)
                                .addComponent(jButton1))))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_editarCurso)
                        .addComponent(btn_consultarProfes)
                        .addComponent(jButton5)
                        .addComponent(btn_editarAlumnos))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4)
                        .addComponent(btn_consultaAlumnos))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EditarProfe c = new EditarProfe();
        c.setVisible(true);
        EditarService<Profesor> editarService = new ProfesorImpl();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_consultarProfesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarProfesActionPerformed
        // TODO add your handling code here:
        ConsultarProfe c = new ConsultarProfe();
        c.setVisible(true);
    }//GEN-LAST:event_btn_consultarProfesActionPerformed

    private void btn_consultaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaAlumnosActionPerformed
        // TODO add your handling code here:
        ConsultarAlumnosdeCursos c = new ConsultarAlumnosdeCursos();
        c.setVisible(true);
    }//GEN-LAST:event_btn_consultaAlumnosActionPerformed

    private void btn_crearEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEstuActionPerformed
        // TODO add your handling code here:
        AsignarAlumno a = new AsignarAlumno();
        a.setVisible(true);
    }//GEN-LAST:event_btn_crearEstuActionPerformed

    private void btn_crearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEstudianteActionPerformed
        // TODO add your handling code here:
        CrearAlumno c = new CrearAlumno();
        c.setVisible(true);
    }//GEN-LAST:event_btn_crearEstudianteActionPerformed

    private void btn_crearProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearProfesorActionPerformed
        // TODO add your handling code here:
        CrearProfesor c = new CrearProfesor();
        c.setVisible(true);
    }//GEN-LAST:event_btn_crearProfesorActionPerformed

    private void btn_consultarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarCursosActionPerformed
        ConsultarCursos c = new ConsultarCursos();
        c.setVisible(true);
    }//GEN-LAST:event_btn_consultarCursosActionPerformed

    private void btn_crearCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearCursosActionPerformed
        // TODO add your handling code here:
        CrearCurso c = new CrearCurso();
        c.setVisible(true);
    }//GEN-LAST:event_btn_crearCursosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConsultarAlumnos c = new ConsultarAlumnos();
        c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Loader_Export.loaderCursosJSON();
        } catch (ParseException | IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Loader_Export.exportAlumnosXML();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Loader_Export.loaderAlumnosXML();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_editarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarAlumnosActionPerformed
        // TODO add your handling code here:
        EditarAlumno c = new EditarAlumno();
        c.setVisible(true);
    }//GEN-LAST:event_btn_editarAlumnosActionPerformed

    private void jButton_editarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarCursoActionPerformed
        // TODO add your handling code here:
        EditarCursos c = new EditarCursos();
        c.setVisible(true);
        EditarService<Curso> editarService = new CursoImpl();

    }//GEN-LAST:event_jButton_editarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultaAlumnos;
    private javax.swing.JButton btn_consultarCursos;
    private javax.swing.JButton btn_consultarProfes;
    private javax.swing.JButton btn_crearCursos;
    private javax.swing.JButton btn_crearEstu;
    private javax.swing.JButton btn_crearEstudiante;
    private javax.swing.JButton btn_crearProfesor;
    private javax.swing.JButton btn_editarAlumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_editarCurso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
