/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb.Estudiante;

import com.mycompany.loginb.Alumno;
import com.mycompany.loginb.Curso;
import com.mycompany.loginb.Loginb;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wil
 */
public class ConsultarCurso extends javax.swing.JFrame {
      int xMouse, yMouse;

    /**
     * Creates new form ConsultarCurso
     */
    public ConsultarCurso() {
        initComponents();
        mostrarCursosAlumnoLogeado();
    }

 public void mostrarCursosAlumnoLogeado() {
    
    // Buscar los cursos del alumno loggeado
    List<Curso> cursosAlumno = Loginb.buscarCursosAlumno(Loginb.alumnoLogeado);

    // Crear el modelo de la tabla
    DefaultTableModel data = new DefaultTableModel(
            new String[]{"Codigo", "Nombre", "Seccion", "Profesor", "Fecha Ini", "Fecha Fin", "Hora Ini", "Hora Fin", "Nota Final"},
            cursosAlumno.size()); // Ajustar el tamaño de la tabla según la lista de cursos

    jTable1.setModel(data);

    int row = 0;

    for (Curso curso : cursosAlumno) {
        // Establecer valores en la fila actual
        jTable1.setValueAt(curso.codigo, row, 0);
        jTable1.setValueAt(curso.nombre, row, 1);
        jTable1.setValueAt(curso.seccion, row, 2);
        jTable1.setValueAt(curso.profesor, row, 3);

        // Formatear y establecer la fecha de inicio
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaIniFormatted = dateFormat.format(curso.fechaIni);
        jTable1.setValueAt(fechaIniFormatted, row, 4);

        // Formatear y establecer la fecha de fin
        String fechaFinFormatted = dateFormat.format(curso.fechaFin);
        jTable1.setValueAt(fechaFinFormatted, row, 5);

        jTable1.setValueAt(curso.horaIni, row, 6);
        jTable1.setValueAt(curso.horaFin, row, 7);
        double notaFinal = Loginb.alumnoLogeado.notasFinales.getNotaFinal(curso.codigo);
        jTable1.setValueAt(notaFinal, row, 8);

        row++;
    }

    // Mensaje si no hay cursos asignados
    if (cursosAlumno.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No tiene cursos asignados.");
    }
}

    

    // Mensaje si no hay cursos asignados
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_designarCurso = new javax.swing.JButton();
        header2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_designarCurso.setText("Designar");
        btn_designarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_designarCursoActionPerformed(evt);
            }
        });

        header2.setBackground(new java.awt.Color(51, 51, 51));
        header2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header2MouseDragged(evt);
            }
        });
        header2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btn_designarCurso)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_designarCurso))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_designarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_designarCursoActionPerformed
        // TODO add your handling code here:
         // Obtener la fila seleccionada
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) { // Verificar que se haya seleccionado una fila
        String codigoCurso = jTable1.getValueAt(selectedRow, 0).toString();
        
        // Quitar al alumno logueado de ese curso
        Loginb.quitarAlumnoCurso(Loginb.alumnoLogeado, codigoCurso);
        JOptionPane.showMessageDialog(this, "Curso eliminado correctamente");
        
        // Actualizar la tabla para reflejar los cambios
        mostrarCursosAlumnoLogeado(); 
    } else {
        // Mostrar un mensaje de error si no se seleccionó ninguna fila
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un curso.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_designarCursoActionPerformed

    private void header2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y- yMouse);
    }//GEN-LAST:event_header2MouseDragged

    private void header2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header2MousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_designarCurso;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
